/**
 * Each new term in the Fibonacci sequence is generated by adding the previous
 * two terms. By starting with 1 and 2, the first 10 terms will be:
 * 
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * 
 * By considering the terms in the Fibonacci sequence whose values do not exceed
 * four million, find the sum of the even-valued terms.
 * 
 * @author praveen
 * 
 */
public class ProjectEuler2 {
	
	public static void main(String args[]) {
		int bound = 4000000;
		int current = 1;
		int previous = 0;
		int sum = 0;
		while(current < bound) {
			int temp = current + previous;
			previous = current;
			current = temp;
			if(current % 2 ==0) {
				sum += current;
			}
		}
		
		System.out.println(sum);
	}

}
